CREATE TABLE jwt_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

CREATE INDEX jwt_logs_user_id_idx ON jwt_logs (user_id);
